// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "fedimint-react-native-bindings.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ReactNativeBindingsSpec.h"

@interface ReactNativeBindings : NSObject <NativeReactNativeBindingsSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeBindings : NSObject <RCTBridgeModule>
#endif

@end