// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <fbjni/fbjni.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "fedimint-react-native-bindings.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_fedimint_reactnative_ReactNativeBindingsModule and fedimint_reactnativebindings
// by comparing the whole line here.
/*
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return fedimint_reactnativebindings::multiply(a, b);
}
*/

// Installer coming from ReactNativeBindingsModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    // WHY THIS PATCH IS NEEDED:
    // The uniffi-bindgen-react-native generator outputs C++ code that manually attempts to
    // extract the CallInvoker from the Java CallInvokerHolder object using JNI reflection.
    // However, in React Native 0.77+ (and the new architecture), the memory layout and standard
    // approaches for hybrid objects changed. The manual reflection approach fails sometimes
    // and causes crashes. Instead, we use the proper fbjni API `facebook::jni::wrap_alias`
    // which is the officially supported way to extract the C++ HybridClass from the Java
    // representation.
    // Reference: https://github.com/realm/realm-js/issues/7011
    auto callInvokerHolder = facebook::jni::wrap_alias(
        reinterpret_cast<facebook::react::CallInvokerHolder::javaobject>(callInvokerHolderJavaObj)
    )->cthis();
    auto jsCallInvoker = callInvokerHolder->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fedimint_reactnativebindings::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_fedimint_reactnative_ReactNativeBindingsModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return fedimint_reactnativebindings::cleanupRustCrate(*runtime);
}