#ifndef FEDIMINT_REACTNATIVEBINDINGS_H
#define FEDIMINT_REACTNATIVEBINDINGS_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace fedimint_reactnativebindings {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* FEDIMINT_REACTNATIVEBINDINGS_H */