rust:
  directory: ../../
  manifestPath: fedimint-client-uniffi/Cargo.toml

bindings:
  name: FedimintReactNativeBindings
  cpp: cpp/generated
  ts: src/generated

android:
  javaPackage: com.fedimint.reactnative
  targets:
    - arm64-v8a
    - x86_64
  useSharedLibrary: true

ios:
  tags: [ios]
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworks: # Needed for rust bindings to work on iOS
    - SystemConfiguration
    - Security
