# NO LONGER USED - the docs site is now being deployed to github pages instead of the example
name: Deploy Vite-Core Example to GitHub Pages

on:
  # Using github pages for docs instead of preview

  # push:
  # branches: ['main']
  # paths: ['js/shared/core/**', 'js/examples/vite-core/**']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Vite-Core Example to GitHub Pages
    environment:
      name: '@fedimint/core + Vite Example'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm --dir js build && pnpm --dir js build:pages

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload dist folder
          path: 'js/examples/vite-core/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
