name: Verify
on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint repo
        run: pnpm --dir js lint:repo

      - name: Lint code
        run: pnpm --dir js lint

  build:
    name: Build JS
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: pnpm --dir js build

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Run unit tests
        run: pnpm --dir js test:unit

  types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build types package
        run: pnpm --dir js --filter @fedimint/types build

      - name: Check types
        run: pnpm --dir js typecheck

  test:
    name: Test
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 45

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build WASM
        uses: ./.github/actions/build-wasm
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run pnpm tests
        shell: bash
        run: |
          nix develop --accept-flake-config .#wasm-tests --command bash << 'EOF'
            set -euo pipefail

            # Install dependencies
            pnpm --dir js install

            # Build packages
            pnpm --dir js build

            # Run Tests
            pnpm --dir js test
          EOF

      - name: Report Size
        uses: alexlwn123/compressed-size-action@alex/fix-build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'js/{shared,web,react-native,tools}/**/{dist/**/*.{js,mjs,cjs},*.wasm}'
          install-script: nix develop --accept-flake-config -c pnpm --dir js install
          build-script: nix develop --accept-flake-config -c pnpm --dir js build

  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build Packages (dependency of docs)
        run: pnpm --dir js build

      - name: Build Docs
        run: pnpm --dir js docs:build
